deepset-ai/haystack-experimental

README.md
The new clarification takes the release date of the corresponding public build into account.
=> docs: Clarify experiment lifecycle

haystack_experimental/evaluation/harness/rag/evaluation_pipeline.py, haystack_experimental/evaluation/harness/rag/harness.py, haystack_experimental/evaluation/harness/rag/parameters.py, pyproject.toml, test/evaluation/harness/rag/test_harness.py
Feedback from @bilgeyucel's review of the example notebook. Also includes some test refactoring to avoid unnecessary failures.
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and fixed any …
=> refactor: Rename identifiers for clarification

haystack_experimental/evaluation/harness/rag/harness.py, haystack_experimental/evaluation/util/pipeline_pair.py
The PR introduced changes to display the progress of the RAG pipeline's execution within the RAG eval harness. Unlike the evaluation pipeline, the harness will run the RAG pipeline in full for every query passed to it. This is because all RAG pipelines expect a single query/input and return a single result, while the evaluation pipeline takes batches of inputs. 
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: …
=> feat: Add support for displaying a progress bar for RAG pipeline execution inside the RAG eval harness

README.md
3 months from the date of the initial public release.
=> Update end dates in README.md

README.md
=> Add note about examples to the Readme

README.md
Add note to the readme about telemetry.
=> docs: Add section about telemetry to the readme

haystack_experimental/components/writers/__init__.py, haystack_experimental/components/writers/chat_message_writer.py, test/components/writers/__init__.py, test/components/writers/test_chat_message_writer.py
- Adds `ChatMessageWriter` and its unit tests
=> feat: Add ChatMessageWriter

haystack_experimental/components/retrievers/__init__.py, haystack_experimental/components/retrievers/chat_message_retriever.py, test/components/retrievers/__init__.py, test/components/retrievers/test_chat_message_retriever.py
- Adds `ChatMessageRetriever` and its unit tests
=> feat: Add ChatMessageRetriever

haystack_experimental/components/generators/chat/openai.py, test/components/generators/chat/test_openai.py
https://github.com/deepset-ai/haystack-experimental/pull/58#discussion_r1724814580
Check that the tool names are unique in `__init__` and `run`
CI, new test
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md …
=> `OpenAIChatGenerator` - check tool names are unique

README.md
-  None
add two new components and the new store to the catalog in the readme.
no tests
=> chore: Add memory components and store to catalog

haystack_experimental/components/splitters/hierarchical_doc_splitter.py
=> docs: fixing typo

docs/pydoc/config/data_classes_api.yml
Accidentally overwrote the data-classes in the core package, so I need to change the file name here :) 
=> docs: Update data_classes_api.yml

docs/pydoc/config/evaluation_harness_api.yml, docs/pydoc/config/generators_api.yml, docs/pydoc/config/retrievers_api.yml, docs/pydoc/config/splitters_api.yml, docs/pydoc/config/tools_api.yml, docs/pydoc/config/writers_api.yml
I overwrote more links than I thought....
=> docs: fixing the slugs and names

haystack_experimental/components/generators/chat/openai.py, haystack_experimental/components/tools/openapi/openapi_tool.py, test/components/generators/chat/test_openai.py, test/components/tools/openapi/test_openapi_tool.py, test/components/tools/test_tool_invoker.py
- part of https://github.com/deepset-ai/haystack/issues/8222
- local unit tests and CI tests
=> feat: changing default model from gpt-3.5-turbo` to `gpt-4o-mini`

haystack_experimental/components/generators/chat/openai.py, haystack_experimental/core/pipeline/async_pipeline.py, haystack_experimental/util/asynchronous.py, test/components/generators/chat/test_openai.py, test/components/splitters/test_hierarchical_doc_splitter.py, test/components/tools/test_tool_invoker.py, test/core/pipeline/features/test_run.py, test/core/pipeline/test_async_pipeline.py
In line with https://github.com/deepset-ai/haystack/pull/8370. Also pulls changes from `haystack@main` w.r.t `PipelineBase`.
Requires 2.6.0 (tests will fail until then).
CI …
=> refactor: Rename `async_run` to `run_async`

haystack_experimental/components/__init__.py
- completing the `__init__.py` the `components` module level
- ran tests locally
=> fix: adding missing components the `__init__.py` at the `components` module level

examples/auto_merging_retriever.ipynb
This PR adds the already merged auto merging cookbook as an example
=> adding auto merging example

haystack_experimental/components/tools/openapi/_openapi.py, haystack_experimental/components/tools/openapi/openapi_tool.py
- linting job is failing: https://github.com/deepset-ai/haystack-experimental/actions/runs/11016791581/job/30593155933
Ignore the specific pylint rule: `too-many-positional-arguments`
CI
pre-commit hook reformatted some code lines
- I ran …
=> fix: fix linting

haystack_experimental/core/pipeline/async_pipeline.py, test/core/pipeline/features/pipeline_run.feature, test/core/pipeline/features/test_run.py
=> fix: Async pipeline tests to accommodate upstream changes

test/components/tools/openapi/conftest.py, test/components/tools/openapi/test_openapi_client_live.py, test/components/tools/openapi/test_openapi_tool.py
- minor fixes around test skipping in open api tool
=> chore: Improve OpenAPI tools test skipping

test/components/extractors/test_llm_metadata_extractor.py
- Unit tests are failing (https://github.com/deepset-ai/haystack-experimental/actions/runs/12301789757/job/34333144062?pr=155) due to https://github.com/deepset-ai/haystack-core-integrations/pull/1244
- adjust the test
CI …
=> fix: fix Bedrock test

haystack_experimental/components/extractors/llm_metadata_extractor.py
- fixes comment raised in this discussion: https://github.com/deepset-ai/haystack-experimental/discussions/130#discussioncomment-11900327
Update example to use correct founding city for HuggingFace
Locally …
=> fxi: Update HF example to correct founding city

examples/pipeline.ipynb
- None
- Remove installation of haystack-experimtal from main branch as the latest release now contains the new `Pipeline` class
- Remove left over import of old Pipeline and Secret
ran on google colab …
=> chore: Update example with new `Pipeline`

test/components/generators/chat/test_openai.py
- reactivates tests accidentally commented out in #180 
=> test: uncomment accidentally commented tests

examples/tracing_pipeline_runs/README.md
=> docs: updating trace comparison tool README.md

docs/pydoc/config/supercomponent_api.yml
=> docs: add MultiFileConverter, SentenceTransformerrsDocumentIndexer, and DocumentPreprocessor to docs

haystack_experimental/components/agents/agent.py
- None
- Add two missing imports to usage example
=> docs: Add missing imports to Agent usage example

examples/pipeline_breakpoints/hybrid_rag_pipeline.py, haystack_experimental/core/pipeline/pipeline.py, pyproject.toml, test/core/pipeline/test_pipeline_breakpoints.py
Added a fix for deserialization errors. Try out this branch and I believe all of the components in hybrid_rag_pipelines are working with breakpoints. But we need to consider some edge cases still.
The docjoiner fix was throwing errors for me.
=> Fix deserilzation errors in resuming

examples/pipeline_breakpoints/prod_pipeline.yml, haystack_experimental/core/pipeline/pipeline.py, test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py, test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py, test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py
- new strategy, remove `sender` from serialisation
- start new deserialisation strategy
=> fix: starting from clean state

examples/pipeline_breakpoints/hybrid_rag_pipeline.py, haystack_experimental/core/pipeline/pipeline.py, test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py, test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py, test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py
=> fix: hybrid pipeline working with stop/resume at each breakpoing

test/core/pipeline/test_pipeline_breakpoints_string_joiner.py
=> feat: adding one more test with `StringJoiner`

pyproject.toml, test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py, test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py, test/core/pipeline/test_pipeline_breakpoints_list_joiner.py, test/core/pipeline/test_pipeline_breakpoints_loops.py, test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py, test/core/pipeline/test_pipeline_breakpoints_string_joiner.py
=> fix: windows tests fails due to not being able to read resume state files

test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py, test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py, test/core/pipeline/test_pipeline_breakpoints_list_joiner.py, test/core/pipeline/test_pipeline_breakpoints_loops.py, test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py
=> fix: adding mocks to tests

.github/ISSUE_TEMPLATE/add_experiment.md
=> Update issue template for adding new experiments

haystack_experimental/core/__init__.py
=> fix: Update __init__.py to use double underscore

docs/pydoc/config/image_converters_api.yml
Small improvements to the Image Converters pydoc config
=> chore: improve Image Converters pydoc config

.github/ISSUE_TEMPLATE/move_experiment_to_core.md, .github/ISSUE_TEMPLATE/remove_experiment.md, pyproject.toml
- follow up of #287
- remove dependencies needed for `MultiFileConverter` (now moved to Haystack)
- add a bullet point for dependencies cleanup in GitHub issue templates
CI …
=> chore: remove dependencies needed for `MultiFileConverter`

README.md
part of #301
- add the multimodal experiment to README
=> chore: update README with multimodal experiment

README.md
- adding missing discussions links
=> docs: adding links + fixing links
