README.md

- fixes n/a
Add context to the readme file. [PREVIEW](https://github.com/deepset-ai/haystack-experimental/blob/massi/readme/README.md)
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and …

Add context to the README

---

haystack_experimental/evaluation/harness/rag/harness.py

Fixes:
- The parameter name for the faithfulness evaluator was outdated.
- The meta names of the expected components were incorrectly being passed to the to `PipelinePair` instead of the component names.
All tests …

fix: Correct parameter name for faithfulness evaluator and fix component names passed to `PipelinePair`

---

haystack_experimental/components/__init__.py
haystack_experimental/components/tools/__init__.py
haystack_experimental/components/tools/openai/__init__.py
haystack_experimental/components/tools/openai/function_caller.py
pyproject.toml
test/components/__init__.py
test/components/tools/__init__.py
test/components/tools/openai/__init__.py
test/components/tools/openai/test_function_caller.py

I propose adding this `OpenAIFunctionCaller` component that is able to accept a list of ChatMessages, and run a function if there were any `tool_calls` within these messages. 
Some simple guardrails that have been added: 
If the tool/function name in the message that we get doesn't actually exist (hallucinated) , the component returns an assistant message indicating as such. 
Manual tests. Here is the pipeline I'm using:
```
message_collector = BranchJoiner(List[ChatMessage])
chat_generator = OpenAIChatGenerator(model="gpt-3.5-turbo", generation_kwargs={'tools': tools})
function_caller = OpenAIFunctionCaller(available_functions={"rag_pipeline_func": rag_pipeline_func, 
"get_current_weather": get_current_weather})
function_calling_pipeline = Pipeline() …
```

adding the OpenAIFunctionCaller

---

haystack_experimental/evaluation/harness/rag/evaluation_pipeline.py
haystack_experimental/evaluation/harness/rag/harness.py
haystack_experimental/evaluation/harness/rag/parameters.py
test/evaluation/harness/rag/test_harness.py

This PR adds support for using the `ContextRelevanceEvaluator` component with the RAG evaluation harness.
Unit tests

feat: Add `ContextRelevanceEvaluator` to RAG eval harness

---

haystack_experimental/evaluation/harness/rag/evaluation_pipeline.py

- LLM-based Evaluators have `raise_on_Failure=False` by default

feat: LLM-based Evaluators have `raise_on_Failure=False` by default

---

haystack_experimental/evaluation/harness/rag/harness.py
test/evaluation/harness/rag/test_harness.py

The ground truth inputs passed to the RAG eval harness were not being included in the final results. This PR rectifies that.
Unit test
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and …

feat: Add ground truth documents and answers to RAG eval run results as inputs

---

README.md

The OpenAIFunctionCaller component was added in https://github.com/deepset-ai/haystack-experimental/pull/14 but it's not listed in the catalogue in the readme yet. This PR adds the OpenAIFunctionCaller to the catalogue.

chore: Add OpenAIFuntionCaller to catalogue

---

haystack_experimental/version.py
pyproject.toml

Streamlines the release process by directly reading the version from the Git tag, like we do with the core integrations.

build: Fetch build version from Git tag

---

.github/workflows/tests.yml
README.md
haystack_experimental/components/tools/openapi/_schema_conversion.py
haystack_experimental/components/tools/openapi/openapi_tool.py
pyproject.toml
test/components/tools/openapi/test_openapi_client_live_anthropic.py
test/components/tools/openapi/test_openapi_client_live_cohere.py

- Moved OpenAPI test dependencies from hatch `envs.default` to `envs.test`

chore: Move OpenAPI test dependencies to hatch test

---

.pre-commit-config.yaml
pyproject.toml

- fixes [#7865](https://github.com/deepset-ai/haystack/issues/7865)
Adds pre-commit hooks to the repo
Manual testing

chore: add pre-commit hooks

---

test/components/tools/openapi/test_openapi_client_live_openai.py

Firecrawl servers repeatedly hit read timeouts, most likely due to popularity of this service and insufficient capacity on their side. Disable for now continue to run manually, revisit in a month or so

chore: Disable OpenAPITool firecrawl integration test

---

docs/pydoc/config/harness.yml
docs/pydoc/config/openai_function_caller.yml
docs/pydoc/config/openapitool.yml

- Updates module syntax from this [format](https://docs.haystack.deepset.ai/v2.3-unstable/reference/evaluation-harness#module-harnessevaluation_harness) to this [format](https://docs.haystack.deepset.ai/v2.3-unstable/reference/integrations-chroma#module-haystack_integrationscomponentsretrieverschromaretriever)
- Verified with local build
This is the rendering of the local md build:

chore: Update module names syntax in generated docs

---

haystack_experimental/evaluation/harness/rag/__init__.py
haystack_experimental/evaluation/harness/rag/harness.py
haystack_experimental/evaluation/harness/rag/parameters.py
test/evaluation/harness/rag/test_harness.py

This PR adds support for evaluating pipelines that do not contain a generator component, i.e., pure retrieval pipelines. With this addition, we have two more "default" architectures to support. To aid consistency, we now expose a `DefaultRAGArchitecture` enumeration that gets passed to the c'tor of `RAGEvaluationHarness`.
Unit tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …

feat/refactor: Allow pipelines without generators to be used with the RAG eval harness

---

examples/rag_eval_harness.ipynb

Add a Google Colab link to the notebook for smooth transition
This is what it looks like
N/A

Add google colab link to the example harness nb

---

examples/rag_eval_harness.ipynb

doc: Fix links to API docs and pip packages in RAG eval harness notebook

---

haystack_experimental/components/tools/openapi/_schema_conversion.py
haystack_experimental/components/tools/openapi/types.py
test/components/tools/openapi/test_openapi_client_edge_cases.py
test/components/tools/openapi/test_openapi_tool.py
test/test_files/yaml/openapi_edge_cases.yml

Improves OpenAPITool's robustness in handling OpenAPI specifications with missing operationIds. Note: operationIds are not required but usually present, this fix handles openapi specs without operationIds
- fixes https://github.com/deepset-ai/haystack/issues/8035
- Enhanced schema conversion to generate custom operationIds when they are missing 
- Having operationIds simplifies operation resolution algorithm 
- Updated type definitions and utility functions to support this change
- Add handling of servers field under path
- Expanded test suite to cover this new functionality
- Implemented logic to create operationIds from path and HTTP method when they are absent:
```python
if "operationId" not in operation_spec:
operation_spec["operationId"] = path_to_operation_id(path, http_method)
``` …

Improve OpenAPITool corner cases handling (missing operationId, servers under paths, etc)

---

haystack_experimental/components/tools/openapi/_payload_extraction.py
haystack_experimental/components/tools/openapi/_schema_conversion.py
haystack_experimental/components/tools/openapi/types.py
test/test_files/yaml/openapi_greeting_service.yml

Centralizes the OpenAPI schema reference resolution -> more simple and maintainable. Spec has references resolved at creation preventing subtle bugs (i.e parameters of an operationId not resolved properly).
- Introduced `jsonref` loading and replacement within the `OpenAPISpecification` class constructor, ensuring all references are resolved upon object instantiation.
- Not user facing
- Ensured existing unit tests for the converter functions passed with the refactored codebase to verify backward compatibility and correctness.
- Adjusted test [yaml service](https://github.com/deepset-ai/haystack-experimental/pull/40/files#diff-35c165d45fc56fa8436798b9114a89947df86be0def29d21e9639411a1527e18) to include parameter reference
- Pay special attention to how jsonref resolution was migrated to …

fix: Centralize OpenAPI schema reference resolution 

---

haystack_experimental/evaluation/harness/rag/_telemetry.py
haystack_experimental/evaluation/harness/rag/harness.py

Add telemetry to the RAG eval harness to provide anonymized usage statistics.
In a follow-up PR, the readMe will be updated to inform users about telemetry in the experimental package. …

feat: Add telemetry to RAG eval harness

---

examples/openapitool.ipynb

For security reasons, https://github.com/deepset-ai/haystack/pull/8095 removed the ability to specify non-native python output types (such as `List[ChatMessage]`).
Unfortunately, this broke the `OpenAPITool` notebook.
I found some alternative ways to do the same.
Something can certainly be improved, but I don't think it is worth the effort.
Manual tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, …

fix: fix `OpenAPITool` notebook

---

docs/pydoc/config/data_classes_api.yml
haystack_experimental/dataclasses/__init__.py
haystack_experimental/dataclasses/chat_message.py
test/dataclasses/test_chat_message.py

- fixes https://github.com/deepset-ai/haystack/issues/8136
I'm overriding the whole module. However, I'm trying not to deviate much from the current implementation...
Notable changes:
- introduce `ToolCall` dataclass to represent a Tool call prepared by the model
- introduce `tool` role for messages containing the results of (external) tool invocations
- drop the support for `function` role (deprecated by OpenAI): I think supporting it properly is not worth it (the world is moving away from this style/mode of doing things). In truth, I would also deprecate it in the Haystack core.
Adapted old tests, new tests.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of …

feat: update `ChatMessage` to support tools

---

pyproject.toml
test/components/tools/openapi/test_openapi_client_live.py
test/components/tools/openapi/test_openapi_client_live_anthropic.py
test/components/tools/openapi/test_openapi_client_live_cohere.py
test/components/tools/openapi/test_openapi_client_live_openai.py
test/components/tools/openapi/test_openapi_tool.py

- Add new marker for tests `unstable`
- Mark all unstable tests and reasons why they fail
- Skip these tests in CI by default
- Run them from command line if needed with:
- `hatch run test:integration -- -m "integration and unstable"` 
Supersedes https://github.com/deepset-ai/haystack-experimental/pull/54

feat: Add unstable marker, mark unstable tests, skip them in CI

---

haystack_experimental/components/tools/openapi/openapi_tool.py

In the main haystack project pull request [8054](https://github.com/deepset-ai/haystack/pull/8054) added a new parameter in chat generator run methods.
Since we didn't use keyword arguments in invocation of the run method of the chat generator in [`openapi_tool.py`](https://github.com/deepset-ai/haystack-experimental/blob/main/haystack_experimental/components/tools/openapi/openapi_tool.py#L161) we need to now use keyword arguments.

fix: `OpenAPITool` - use keyword args for chat generator run invocation

---

docs/pydoc/config/generators_api.yml

Add missing pydoc configs for classes added in #53 and #57

docs: add pydoc configs for `Tool` and `OpenAIChatGenerator`

---

haystack_experimental/core/__init__.py
haystack_experimental/core/pipeline/__init__.py
haystack_experimental/core/pipeline/async_pipeline.py
pyproject.toml
test/core/__init__.py
test/core/pipeline/__init__.py
test/core/pipeline/features/README.md
test/core/pipeline/features/conftest.py
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py
test/core/pipeline/test_async_pipeline.py

- soft-dependency on https://github.com/deepset-ai/haystack/pull/8279 
Introduces the `AsyncPipeline` class that supports `async` Python runtimes. Uses the same execution logic as a regular `Pipeline` with the following changes:
- The `run` method of the `AsyncPipeline` returns an asynchronous generator that yields the outputs of executed components immediately after they are run.
- This allows for the streaming of intermediate results in an async environment, e.g: a RAG pipeline can yield the results of the retriever before the generator is run.
- The last output yielded by the `run` method is the pipeline's final output.
- Since method is a generator, the execution of the pipeline can only progress if its outputs are consumed. Turning that around, it allows the user to determine - after …

feat: Implement `AsyncPipeline`

---

haystack_experimental/components/retrievers/chat_message_retriever.py
test/components/retrievers/test_chat_message_retriever.py

Enhances the `ChatMessageRetriever` component by introducing a `last_k` parameter allowing for selective retrieval of a specified number of recent chat messages. This change addresses the need for more control in accessing chat history, particularly in scenarios where only the most recent interactions are relevant.
- fixes https://github.com/deepset-ai/haystack/issues/8258
- Added `last_k` as init parameter to match the existing pattern in other retrievers (defaults to 10)
- Added an `Optional[int]` parameter named `last_k` to the `run` method of the `ChatMessageRetriever`, enabling selection of the number of recent messages to retrieve.
- Implemented validation to ensure `last_k` is greater than 0 when specified, raising a `ValueError` if not.
- Expanded unit tests to cover new …

feat: Adds `last_k` parameter to `ChatMessageRetriever` init/run methods

---

haystack_experimental/components/generators/chat/openai.py
haystack_experimental/dataclasses/__init__.py
haystack_experimental/dataclasses/streaming_chunk.py
haystack_experimental/util/__init__.py
haystack_experimental/util/asynchronous.py
test/components/generators/chat/test_openai.py
test/components/tools/test_tool_invoker.py

- related to https://github.com/deepset-ai/haystack/issues/6012
Adds support for async in `OpenAIChatGenerator`. Also includes a couple of unrelated changes/fixes:
- Fix missing init params `timeout` and `max_retries` in serde.
- Update the default model to `gpt-4o-mini` in line with the core package.
Unit and integration tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …

feat: Implement async support for `OpenAIChatGenerator`

---

haystack_experimental/components/retrievers/auto_merging_retriever.py

- AstraDB is now also supported by the AutoMergingRetreiver

docs: AutoMerging Retriever now supports AstraDB

---

test/document_stores/opensearch/test_document_store.py

Locally
Test will fail on the CI until 2.6.0's release.

tests: Skip OpenSearch tests if the test backend is inactive

---

test/components/tools/openapi/test_openapi_tool.py

- adds skipif marker to `test_allowed_operations` unit test (fork repo sensitive test)
- mark `test_run_live_meteo_forecast_with_non_normalized_operation_id` as `unstable` as meteo service can be often down

chore: Update OpenAPITool tests

---

haystack_experimental/document_stores/in_memory/__init__.py
haystack_experimental/document_stores/in_memory/document_store.py
haystack_experimental/document_stores/types/protocol.py
test/document_stores/test_in_memory.py

- https://github.com/deepset-ai/haystack/issues/6012
Add support for async in `InMemoryDocumentStore`.
Unit tests
CI will fail due to a dependency on core 2.6.0. Test locally. …

feat: Implement async version of `InMemoryDocumentStore`

---

haystack_experimental/components/extractors/llm_metadata_extractor.py

fix: adding forward references for integration generations in `LLMMetadataExtractor`

---

.github/workflows/tests.yml
README.md
docs/pydoc/config/generators_api.yml
haystack_experimental/components/__init__.py
haystack_experimental/components/generators/ollama/__init__.py
haystack_experimental/components/generators/ollama/chat/__init__.py
haystack_experimental/components/generators/ollama/chat/chat_generator.py
haystack_experimental/dataclasses/chat_message.py
pyproject.toml
test/components/generators/ollama/test_chat_generator.py

- fixes https://github.com/deepset-ai/haystack/issues/8190
I'm adding support for tools in `OllamaChatGenerator`. Similar to OpenAI PR #57.
I'm trying to respect a balance between introducing new things and being compatible with existing code.
CI, new tests.
I manually tested the Chat Generator using our [notebook](https://github.com/deepset-ai/haystack-experimental/blob/main/examples/tools_support.ipynb).
The implementation generally works well.
The simple use case and processing tool results with the Chat Generator are fully reproducible.
Reproducing the multi-tool chat application (with human in the loop) is not always stable with `llama3.2:3b`/`llama3.1:8b`.
The model tends to produce tool calls (even if not needed) and sometimes hallucinates tools.
Also, Ollama support for tools is …

feat: support for tools in `OllamaChatGenerator`

---

test/components/splitters/test_hierarchical_doc_splitter.py
test/components/tools/test_tool_invoker.py

https://github.com/deepset-ai/haystack/pull/8354
Some tests are failing due to the renaming of this argument: https://github.com/deepset-ai/haystack-experimental/actions/runs/11162240813/job/31026461862?pr=114
Rename the argument in tests, too
CI …

chore: replace `max_loops_allowed` with `max_runs_per_component` in tests

---

docs/pydoc/config/writers_api.yml
haystack_experimental/components/writers/__init__.py
haystack_experimental/components/writers/document_writer.py
test/components/writers/test_document_writer.py

- https://github.com/deepset-ai/haystack/issues/6012
Adds async support to the `DocumentWriter` component
Unit test
CI will fail until 2.6.0 is out. Test locally with `haystack@main`. …

feat: Implement async support in `DocumentWriter`

---

haystack_experimental/components/generators/ollama/chat/chat_generator.py
pyproject.toml
test/components/generators/ollama/test_chat_generator.py

- tests failing: https://github.com/deepset-ai/haystack-experimental/actions/runs/11365200366/job/31612862722?pr=118
- a new parameter was added in `OllamaChatGenerator` with https://github.com/deepset-ai/haystack-core-integrations/pull/1131
Adapt the experimental component to take this new parameter into account
CI, adapted tests
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, …

fix: update `OllamaChatGenerator` with `keep_alive` parameter

---

haystack_experimental/components/retrievers/opensearch/__init__.py
haystack_experimental/components/retrievers/opensearch/bm25_retriever.py
haystack_experimental/components/retrievers/opensearch/embedding_retriever.py
test/components/retrievers/opensearch/test_embedding_retriever.py

- https://github.com/deepset-ai/haystack/issues/6012
Add support for async to the `OpenSearchEmbeddingRetriever` and some minor bug fixes.
Unit tests
Test failures should be unrelated; lints will be fixed when the feature branch is merged into `main`.
- I documented my …

feat: Add async support to `OpenSearchEmbeddingRetreiver`

---

pyproject.toml

Tests in PRs are failing: https://github.com/deepset-ai/haystack-experimental/actions/runs/11498274042/job/32003723182?pr=125
This is due to the release of `transformers==4.46.0`, which has a type hint incompatible with Python<3.9
https://github.com/huggingface/transformers/issues/34370
We were not pinning `transformers` in this repository, so we get the latest version.
(We should soon drop support for python 3.8, which reached EOL.)
Pin `transformers<4.46.0`
CI
- I've used …

ci: pin `transformers<4.46.0`

---

test/evaluation/harness/rag/test_harness.py

To accommodate the recent Haystack [PR](https://github.com/deepset-ai/haystack/pull/8473) related to serialization constraints.
Unit tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) …

fix: Update mock components in eval harness test to correctly serialize their params

---

haystack_experimental/components/generators/anthropic/chat/chat_generator.py
haystack_experimental/components/generators/chat/openai.py
test/components/generators/anthropic/test_anthropic.py
test/components/generators/chat/test_openai.py

While experimenting in an application with several Chat Generators,
I encountered some errors passing `ChatMessages` generated by OpenAI to Anthropic.
Our implementation of OpenAI always creates a `TextContent`. Anthropic fails with empty text blocks.
**I think we should not create a "" `TextContent` if `content` is `None`. We should simply avoid creating it**
Do not create `TextContent` if `content` is `None`.
CI, enriched existing tests
- I've used one of the [conventional …

fix: OpenAI Chat Generator - do not create `TextContent` if `content` is `None`; make Anthropic Chat Generator more robust

---

haystack_experimental/core/pipeline/async_pipeline.py
test/core/pipeline/features/conftest.py
test/core/pipeline/features/pipeline_run.feature
test/core/pipeline/features/test_run.py

Port the recent changes to the pipeline run logic into `AsyncPipeline`
Unit tests
The primary changes to the existing code:
- `_run_component` calls the `run_async` method of the component if it exists. If not, launch the `run` method on an executor in the current event loop.
- `includes_outputs_from` is removed as pipeline's run method returns an async iterator. The old behaviour can be reproduced with the new `run_async_pipeline` helper function.
- `_run_subgraph` yields the output of each component greedily.
The test are copied from the core package. The lints might fail, but they will be fixed when the `async-experiments` branch is merged into `main`.
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of …

refactor: Port subgraph pipeline logic and tests to async pipelines

---

haystack_experimental/components/generators/chat/openai.py
haystack_experimental/components/tools/openai/function_caller.py
haystack_experimental/components/tools/openapi/openapi_tool.py
haystack_experimental/components/tools/tool_invoker.py

- fixes deepset-ai/haystack#8170
Set `ensure_ascii=False` when dumping to JSON tool or function calls, this way special chars like emojis are not lost.
I tested manually.
N/A …

Disable `ensure_ascii` when dumping to json tool responses

---

haystack_experimental/components/generators/ollama/chat/chat_generator.py
pyproject.toml
test/components/generators/ollama/test_chat_generator.py

- similar to https://github.com/deepset-ai/haystack-core-integrations/pull/1209
- yesterday, a new version of the Ollama python client was released: they introduce pydantic and this breaks some of our assumptions to use python dictionaries
- See https://github.com/ollama/ollama-python/releases/tag/v0.4.0; https://github.com/ollama/ollama-python/pull/276
- update our code to make it work with `ollama>=0.4.0`
- depend on `ollama-haystack>=2.0.0` (which pins `ollama>=0.4.0` and works properly with this version)
CI
- I added …

fix: adapt to Ollama client 0.4.0

---

docs/pydoc/config/retrievers_api.yml
haystack_experimental/components/retrievers/in_memory/__init__.py
haystack_experimental/components/retrievers/in_memory/bm25_retriever.py
haystack_experimental/components/retrievers/in_memory/embedding_retriever.py
haystack_experimental/components/writers/document_writer.py
test/components/retrievers/test_in_memory_bm25_retriever.py
test/components/retrievers/test_in_memory_embedding_retriever.py

- https://github.com/deepset-ai/haystack/issues/6012
Add async support to `InMemoryBM25Retriever` and `InMemoryEmbeddingRetriever`. And a fly-by doc fix.
Integration tests …

feat: Add async support to `InMemoryBM25Retriever` and `InMemoryEmbeddingRetriever`

---

haystack_experimental/core/pipeline/async_pipeline.py

Related to PR deepset-ai/haystack#8576
Add missing `parent_span` when running cycles in a Pipeline.
I tested the functionality from the original PR, given that the code is basically identical this should work too.
N/A …

Add missing parent span when running cycle in async Pipeline

---

docs/pydoc/config/builders_api.yml
haystack_experimental/components/builders/__init__.py
haystack_experimental/components/builders/chat_prompt_builder.py
haystack_experimental/dataclasses/chat_message.py
test/components/builders/__init__.py
test/components/builders/test_chat_prompt_builder.py

Since the newly-introduced `ChatMessage` dataclass in experimental defers in type signature, components in the core package that consume the above dataclass are no longer able to use the new version due to the type-checking constraints of the pipeline and breaking changes to the class.
This PR updates one such component to use the new version of the `ChatMessage` dataclass. Other components will be duly updated once tool support has been merged into the core package.
Unit tests
- I added unit tests and updated the …

feat: Add support for the new `ChatMessage` data class in `ChatPromptBuilder`

---

haystack_experimental/components/extractors/llm_metadata_extractor.py
pyproject.toml
test/components/extractors/test_llm_metadata_extractor.py

Updates to the LLM Metadata Extractor. 
**Output Changes:**
- Returns `documents` which contains all documents that succeeded in metadata extraction and `failed_documents` which contains all documents that failed (either because the LLM could not be executed or a JSON parsing error). By having this separation it's easy to use the `failed_documents` directly in another LLM metadata extractor to try and fix the issue especially if the error is related to JSON parsing. 
**Prompt Changes**
- Removes the prompt_variable 
- Instead we require the prompt variable to have to be `document`. This way we can utilize all the info contained within a document as well. E.g. I can use `document.content` to print out the contents and then also use `document.meta.XX` to print out any relevant meta …

feat: Metadata extractor update

---

haystack_experimental/components/generators/chat/openai.py

Only add the "strict" dictionary to the openai_tools for generation, if tools_strict is available.
This ensures compatibility with vLLM (which adopts the OpenAI Interface). vLLM throws an error, if the "strict" dictionary is part of the tools list:
`openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'extra_forbidden', 'loc': ('body', 'tools', 0, 'function', 'strict'), 'msg': 'Extra inputs are not permitted', 'input': False}`
- I've used one of …

feat: Update handling of tools_strict to ensure compatibility with vLLM

---

test/components/generators/anthropic/test_anthropic.py

Update to the latest Anthropic usage format i.e. more specifically `MessageStartEvent` changed a bit to include more usage token fields

chore:Format change in Anthropic response

---

haystack_experimental/components/__init__.py
test/components/extractors/test_llm_metadata_extractor.py

Make the imports in test as specific as possible, to avoid importing/testing other components when locally testing a single component.
- local unit tests, 
- integration tests, manual verification
- CI tests …

chore: avoid exporting components to the components package

---

test/chat_message_stores/test_in_memory_chat_message_store.py
test/components/retrievers/test_chat_message_retriever.py
test/components/writers/test_chat_message_writer.py

- part of https://github.com/deepset-ai/haystack/issues/8583
Small test adaptations for making the tests of ChatMessage retriever and writer compatible with both new and old API
CI; local test with Haystack main …

chore: make tests for `ChatMessage` retriever and writer compatible with the new API

---

haystack_experimental/components/splitters/hierarchical_doc_splitter.py
pyproject.toml
test/components/splitters/test_hierarchical_doc_splitter.py

- The `HierarchicalDocumentSplitter` relies on the `DocumentSplitter` to build different hierarchy levels. The DocumentSplitter now needs to be warmup if it's meant to `split_by="sentence"`. Therefore in the `HierarchicalDocumentSplitter`is configured to `split_by="sentence"` needs to call the `.warm_up()` on all the different splitters for each level.
- manual verification  + CI tests
- I've used one of the [conventional commit …

splitters need to be warmed up

---

pyproject.toml

- related PR https://github.com/deepset-ai/haystack-experimental/pull/171 had failures that didn't occur in Haystack core: https://github.com/deepset-ai/haystack-experimental/actions/runs/12871671575/job/35885456412
- add pylint rules in the same way as they are in Haystack core here: https://github.com/deepset-ai/haystack/blob/main/pyproject.toml#L243
-
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, …

chore: make pylint rules consistent with Haystack core

---

haystack_experimental/components/extractors/llm_metadata_extractor.py
test/components/extractors/test_llm_metadata_extractor.py

- partially part of [#8785](https://github.com/deepset-ai/haystack/issues/8785) - changing `LLMMetadaExtractor` to use ChatGenerators
- local unit tests + manual verification + CI tests …

refactor: changing `LLMMetadaExtractor` to use chat generators

---

docs/pydoc/config/document_stores_api.yml
docs/pydoc/config/evaluation_harness_api.yml
docs/pydoc/config/generators_api.yml
docs/pydoc/config/retrievers_api.yml
docs/pydoc/config/splitters_api.yml
docs/pydoc/config/supercomponent_api.yml
docs/pydoc/config/writers_api.yml
docs/pydoc/supercomponent_api.yml

- fixes #191 
- Add SuperComponent pydoc
- Delete outdated experiment pydoc
- Rearrange the order

docs: add Supercomponent pydoc, delete outdated

---

test/components/retrievers/test_auto_merging_retriever.py

- fixes [201](https://github.com/deepset-ai/haystack-experimental/issues/201)
- replace hard-coded doc ids with a programmatic way to find them
- unit tests + manual verification …

fix: fixing auto-merging tests, removing hard-coded doc ids

---

docs/pydoc/config/agents_api.yml

- fixes #207 
- Add pydoc config file for Agent

docs: add pydoc config for Agent component

---

.github/workflows/api_docs.yml

- @dfokina found out that the workflow syncing api docs to readme didn't run as expected. Instead of syncing to verion "2.11-unstable" it synced to "2.9" https://github.com/deepset-ai/haystack-experimental/actions/runs/13563536516/job/37911422196?pr=210
That's because this command in the workflow returns
https://github.com/deepset-ai/haystack-experimental/blob/a04539623a7d6194efd64e8cba9ca71eb19924a3/.github/workflows/api_docs.yml#L25
and the command right after return version numbers in alphabetical order instead of sorted by major.minor version
`["2.0","2.1","2.10","2.11-unstable","2.2","2.3","2.4","2.5","2.6","2.7","2.8","2.9"]`
- Sort versions returned by readme by major and minor version before filtering the top SYNC_LAST_N_HAYSTACK_VERSIONS.
Ran parts of the workflow locally: …

build: sort version numbers by major, minor instead of alphabetic

---

haystack_experimental/components/agents/agent.py
test/components/agents/__init__.py
test/components/agents/test_agent.py

- fixes [#212](https://github.com/deepset-ai/haystack-experimental/issues/212)
Use the correct tool class to deserialize tools
unit tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and …

fix: Agent should deserialize tools with the right class

---

haystack_experimental/components/agents/agent.py

- #212 
- #213
- deserialize `Tools` with the correct class using the available utility function `deserialize_tools_inplace`
CI
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and fixed any …

chore: use `deserialize_tools_inplace` to deserialize tools in `Agent`

---

README.md

- removing dead/wrong links in the discontinued experiments section

chore: removing wrong links for discontinued experiments

---

haystack_experimental/components/agents/agent.py
haystack_experimental/components/writers/__init__.py
test/components/agents/test_agent.py

- partially addresses https://github.com/deepset-ai/haystack-experimental/issues/219 but does not add streaming to tools yet
Allow users to set a streaming callback on the Agent at init and run time.
unit tests …

feat: Agent can stream ChatGenerator responses

---

haystack_experimental/tools/component_tool.py
test/tools/test_component_tool.py

- related to https://github.com/deepset-ai/haystack/issues/9011
To unblock building agents with ComponentTools, we fix the error from the referenced issue here until we find a more comprehensive fix.
unit test …

fix: Jinja2-based ComponentTools in pipelines properly handle deepcopy

---

haystack_experimental/components/tools/tool_invoker.py
haystack_experimental/tools/component_tool.py
haystack_experimental/tools/from_function.py
haystack_experimental/tools/tool.py
test/components/tools/test_tool_invoker.py
test/tools/test_component_tool.py
test/tools/test_from_function.py
test/tools/test_tool.py

- partially addresses https://github.com/deepset-ai/haystack-experimental/issues/237
Specifically the first task of renaming the new variables added to Tool to make them more clear
Finish rename of inputs and outputs to inputs_from_state and outputs_to_state
Updated tests
**Note**: This is a breaking change
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, …

refactor: Rename `inputs` to `inputs_from_state` and `outputs` to `outputs_to_state`

---

haystack_experimental/super_components/converters/multi_file_converter.py
test/super_components/converters/test_multi_file_converter.py

- None. I realized `MultiFileConverter` can only be a drop in replacement of the Router-Converters-Joiner combo if we also expose `unclassified`.
- Add `unclassified` to `MultiFileConverter` `output_mapping`
- Extend integration test
- Extended integration test
- Notebook on Google colab: https://colab.research.google.com/drive/1eM0LmSgh30vCd2e58ucA7n_jnw7H3kGh?usp=sharing
I added some pipeline visualizations for reference below.
- I've used one of the [conventional commit …

feat: Add `unclassified` to output of MultiFileConverter

---

haystack_experimental/components/tools/tool_invoker.py
haystack_experimental/dataclasses/state.py
haystack_experimental/dataclasses/state_utils.py
test/components/tools/test_tool_invoker.py
test/dataclasses/test_state.py
test/dataclasses/test_state_utils.py

- partially addresses https://github.com/deepset-ai/haystack-experimental/issues/237
Addresses these points in the check list
**Tools** and **ToolInvoker**
**State**
Updated tests …

feat: Updates to insertion of values into `State`

---

haystack_experimental/tools/tool.py
test/tools/test_tool.py

- fixes https://github.com/deepset-ai/haystack/issues/9050
Adds the error message from the original exception when raising the ToolInvocationError. This allows us to provide the underlying error in the ChatMessage when using the ToolInvoker so the LLM has a chance to fix the issue.
Updated test
- I've used one of the [conventional commit types](https://www.conventionalcommits.org/en/v1.0.0/) for my PR title: `fix:`, `feat:`, `build:`, `chore:`, `ci:`, `docs:`, `style:`, …

feat: Added original error message to ToolInvocationError

---

haystack_experimental/core/super_component/super_component.py
haystack_experimental/core/super_component/utils.py
test/core/super_component/test_super_component.py
test/core/super_component/test_utils.py
test/super_components/converters/test_multi_file_converter.py

Streamlined SuperComponent to reduce duplicate code. 
Some notable changes:
* We always produce an input mapping and output mapping at init time. Either user provided or one created automatically based on pipeline.inputs() and pipeline.outputs()
* Since we always have a mapping now, we were able to reduce the number of runtime functions. 
* Check that the component is warmed up during runtime. This was missing before but now correctly raises a RuntimeError if not warmed up. 
* Updated docstrings
* Existing tests
* Expanded tests
- I have updated the related issue …

refactor: Streamline super components input and output mapping logic

---

haystack_experimental/components/agents/agent.py
test/components/agents/test_agent.py

@anakin87 and I had a discussion about the internals of the Agent and that it was difficult to understand the logic of the underlying pipeline. 
Additionally, the mermaid picture of the pipeline powering the Agent seems to me to be similarly confusing
This my proposal for changing the Agent to use an explicit python loop to run the agent rather than using a pipeline.
Pros of this approach:
- Makes the logic easier to follow and understand. I also believe that this will make it easier for us to extend the functionality of the Agent in the future and allow for more sophisticated error handling (if we so desire)
- Reduce the number of needed Haystack components from 5 to 2
- No longer have to understand or extend Jinja2 templates to check exit conditions
- Can explicitly use …

Proposal for changing internal working of Agent

---

haystack_experimental/core/pipeline/pipeline.py

- The input for the final component, where the pipeline is stopped, was not being stored. As a result, resuming the pipeline led to a state with no valid entry point.
- There was no mechanism to deserialize inputs that use data classes, which cannot be directly passed to components as dictionaries.
- Store `component_inputs` for the last component in the debug state JSON file.
- Add a deserialization function to reconstruct inputs from Haystack data classes.
- Make `resume_state` a class variable so that the deserialization function is invoked only once.
- Include a `_type` field in the stored input state to support proper deserialization. 
Ran some examples locally.
This is a first proposed solution for a relatively larger issue of deserialization, which can be improved in future.
- I …

fix: Update the resuming function to prevent pipeline deadlocks

---

haystack_experimental/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py
test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py
test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py

fix: removing all sender keys before serialisation

---

haystack_experimental/core/pipeline/pipeline.py

Chat messages are not serialized properly.

Fix major bugs in serialization

---

haystack_experimental/core/pipeline/pipeline.py
pyproject.toml
test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py

- Adaptor will need `unsafe=True` for the break/resume to work properly
- Another edge case of a Joiner having an extra list in serialisation/deserialisation process
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRI …

fix: `Adaptor` will need `unsafe=True` for the break/resume to work properly

---

haystack_experimental/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py
test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py
test/core/pipeline/test_pipeline_breakpoints_list_joiner.py
test/core/pipeline/test_pipeline_breakpoints_loops.py
test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py
test/core/pipeline/test_pipeline_breakpoints_string_joiner.py

Instead of passing the state file path, we allow the user to call `load_state` and pass the state to `run` method to resume the pipeline. This was requested by Thomas.

Revert internal call to pipeline_load state

---

haystack_experimental/core/pipeline/pipeline.py
test/core/pipeline/test_pipeline_breakpoints_answer_joiner.py
test/core/pipeline/test_pipeline_breakpoints_branch_joiner.py
test/core/pipeline/test_pipeline_breakpoints_list_joiner.py
test/core/pipeline/test_pipeline_breakpoints_loops.py
test/core/pipeline/test_pipeline_breakpoints_rag_hybrid.py

- fixes #284 
Added functionality to preserve initialization parameters in debug state. When parameters are defined in component initialization but null in the run method, we now automatically restore the original init values in the saved pipeline state for improved debugging.

fix: preserve initialization parameters in debug state when run params are not supplied 

---

haystack_experimental/components/image_converters/file_to_image.py
haystack_experimental/components/image_converters/pdf_to_image.py
haystack_experimental/dataclasses/chat_message.py
test/dataclasses/test_chat_message.py

- part of https://github.com/deepset-ai/haystack/issues/9258
- add `ImageContent.from_file_path` class method
- add `ImageContent.from_url` class method
CI; several new unit tests
- I decided to reuse the existing components in these class methods (`ImageFileToImageContent` and `LinkContentFetcher`) to avoid duplication and reduce maintenance efforts
- One aspect I want to discuss is MIME type: in the current implementation of these class methods, the user is free to set it and in this case we don't infer it from file path/URL content type. To keep the code simple, an alternative would be to remove this parameter entirely and always infer the MIME type. Given a file path or URL, MIME type inference is generally reliable. What do you think?
- I have read the [contributors …

feat: add convenience class methods to `Imagecontent`

---

haystack_experimental/dataclasses/chat_message.py
haystack_experimental/utils/__init__.py
haystack_experimental/utils/jinja_chat_extension.py
test/dataclasses/test_chat_message.py
test/utils/test_jinja_chat_extension.py

- part of https://github.com/deepset-ai/haystack/issues/9260: I'm not yet modifying the `ChatPromptBuilder` but introducing the foundations to make it work
- introduce a Jinja2 ChatMessage extension
1. The `{% message %}` tag is used to define a chat message.
2. The message can contain text and other structured content parts.
3. To include a structured content part in the message, the `| for_template` filter is used.
The filter serializes the content part into a JSON string and wraps it in a `<haystack_content_part>` tag.
4. The `_build_chat_message_json` method of the extension parses the message content parts,
converts them into a `ChatMessage` object and serializes it to a JSON string.
5. The obtained JSON string will be usable in the `ChatPromptBuilder` component, where templates are …

feat: add Jinja2 ChatMessage extension

---

haystack_experimental/dataclasses/image_content.py
test/dataclasses/test_image_content.py

- fixes https://github.com/deepset-ai/haystack/issues/9364
- add `ImageContent.show()` method to display the underlying image
- in Jupyter, uses [`IPython.display.display`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display)
- in other platforms, uses [`PIL.Image.show`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.show), which calls the appropriate executable depending on the operating systems
CI; new tests
[Example notebook](https://colab.research.google.com/drive/1vPBa58BcHFjL_RBU4LMzn36T0EqbLH7U?usp=sharing)
- I have read the [contributors guidelines](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md) and the [code of conduct](https://github.com/deepset-ai/haystack/blob/main/code_of_conduct.t …

feat: `ImageContent` visualization

---

haystack_experimental/dataclasses/image_content.py
test/dataclasses/test_image_content.py

When experiment in a fresh virtual environment with `ImageContent`, I got
`ModuleNotFoundError: No module named 'IPython'`
- move the IPython import inside the `if is_in_jupyter():` condition
CI, updated test. Also tested locally in a fresh virtual environment
- I …

fix: move IPython import

---

haystack_experimental/components/image_converters/document_to_image.py

- linting failing on main: https://github.com/deepset-ai/haystack-experimental/actions/runs/15486519469/job/43602322860
- I merged #315 without first merging main
- format `DocumentToImageContent`
CI …

chore: fix format for `DocumentToImageContent`

---

haystack_experimental/components/generators/chat/amazon_bedrock.py

- I just released a new version of `amazon-bedrock-haystack`, shipping type support implemented in https://github.com/deepset-ai/haystack-core-integrations/pull/1925
- Now mypy complains: https://github.com/deepset-ai/haystack-experimental/actions/runs/15586489977/job/43893927159?pr=319
- Ignore mypy errors: monkey patches are tricky and mypy is expected to complain now that `amazon-bedrock-haystack` types are usable in downstream libraries.
CI
- I've used one of the …

chore: ignore type errors in Bedrock monkey patches

---

haystack_experimental/components/image_converters/document_to_image.py
test/components/image_converters/test_document_to_image_content.py

Update DocumentToImageContent to store the file path in meta as a string and not as a Path object
added unit tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#installation) and …

fix: Fix storage of file path in ImageContent

---

haystack_experimental/components/embedders/image/sentence_transformers_doc_image_embedder.py
test/components/embedders/test_sentence_transformers_doc_image_embedder.py

Add normalize_embeddings to SentenceTransformersDocumentImageEmbedder to match signature of other embedders in Haystack
updated unit tests
- I ran [pre-commit hooks](https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTIN …

feat: Add `normalize_embeddings` to `SentenceTransformersDocumentImageEmbedder` to match signature of other embedders

---

haystack_experimental/components/converters/image/__init__.py
haystack_experimental/components/converters/image/document_to_image.py
haystack_experimental/components/converters/image/image_to_document.py
test/components/converters/image/test_image_to_document.py

- partially addresses https://github.com/deepset-ai/haystack/issues/9321
Add a `ImageFileToDocument` converter so images can be converted from sources into Documents and then handed off to DocumentWriter or Image Document Embedder. 
Here is an example indexing + query pipeline showing how this can be used. Run this script from within the top-level directory of this repo to properly load all sources.
<details>
<summary> Indexing Example </summary>
```python
import os
from pathlib import Path
from typing import List
os.environ["TOKENIZERS_PARALLELISM"] = "false"
from haystack import Pipeline
from haystack.components.converters.docx import DOCXToDocument
from haystack.components.converters.pypdf import PyPDFToDocument
from haystack.components.embedders.sentence_transformers_document_embedder …
```

feat: Add ImageFileToDocument converter

---

pyproject.toml
test/components/generators/chat/amazon_bedrock/test_chat_generator_utils.py

Tests in experimental are failing (https://github.com/deepset-ai/haystack-experimental/actions/runs/16069230738/job/45349882428?pr=328) after we released a new version of Bedrock, which includes https://github.com/deepset-ai/haystack-core-integrations/pull/2042
- align Bedrock experimental tests to those in core-integrations
- unrelated: I'm also updating transformers version to keep it aligned with Haystack
CI
- I've used one of the [conventional commit …

test: update Bedrock tests with ComponentInfo

---

pyproject.toml

When testing core integrations, I noticed an unexpected dependency structure:
- Haystack depends on Haystack experimental
- Haystack experimental depends on Haystack >=2.15.0 (pin introduced in https://github.com/deepset-ai/haystack-experimental/pull/332)
This setup reduces the effectiveness of our lower-bounds testing in core integrations:
even when we attempt to test Haystack against older supported versions, the dependency on experimental forces an upgrade to >=2.15.0, overriding those bounds.
This has a few implications:
- It limits flexibility for downstream users and complicates dependencies resolution
- The pin is not necessary, especially now that the breakpoint feature has been merged into Haystack.
- unpin haystack
CI
To actually make this change effective, we would need to …

chore: unpin Haystack

---

README.md

- None. Related PR https://github.com/deepset-ai/haystack-experimental/pull/359
- Add GitHub discussion link and jupyter notebook link to README for experimental OpenAIChatGenerator …

chore: Add discussion and cookbook link to OpenAIChatGenerator in README
